### ISSUE TITLE
MySQL errors

### ISSUE THREAD

**Issue by drizuid** [acobaugh/shinobi-docker#5]
during docker-compose up: https://pastebin.com/NwXhVUrL

mysql_1    | MySQL init process done. Ready for start up.
mysql_1    |
mysql_1    | 2019-04-03T13:54:27.414708Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1    | 2019-04-03T13:54:27.416558Z 0 [Note] mysqld (mysqld 5.7.25) starting as process 1 ...
mysql_1    | 2019-04-03T13:54:27.420865Z 0 [Note] InnoDB: PUNCH HOLE support available
mysql_1    | 2019-04-03T13:54:27.420892Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1    | 2019-04-03T13:54:27.420899Z 0 [Note] InnoDB: Uses event mutexes
mysql_1    | 2019-04-03T13:54:27.420905Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql_1    | 2019-04-03T13:54:27.420911Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql_1    | 2019-04-03T13:54:27.420917Z 0 [Note] InnoDB: Using Linux native AIO
mysql_1    | 2019-04-03T13:54:27.421228Z 0 [Note] InnoDB: Number of pools: 1
mysql_1    | 2019-04-03T13:54:27.421363Z 0 [Note] InnoDB: Using CPU crc32 instructions
mysql_1    | 2019-04-03T13:54:27.423427Z 0 [Note] InnoDB: Initializing buffer pool, total size = 1G, instances = 8, chunk size = 128M
mysql_1    | 2019-04-03T13:54:27.479052Z 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_1    | 2019-04-03T13:54:27.487942Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_1    | 2019-04-03T13:54:27.499979Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
mysql_1    | 2019-04-03T13:54:27.586679Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1    | 2019-04-03T13:54:27.586758Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_1    | 2019-04-03T13:54:27.758010Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_1    | 2019-04-03T13:54:27.759269Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql_1    | 2019-04-03T13:54:27.759279Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
mysql_1    | 2019-04-03T13:54:27.759622Z 0 [Note] InnoDB: Waiting for purge to start
mysql_1    | 2019-04-03T13:54:27.809769Z 0 [Note] InnoDB: 5.7.25 started; log sequence number 12360853
mysql_1    | 2019-04-03T13:54:27.809999Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1    | 2019-04-03T13:54:27.810285Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql_1    | 2019-04-03T13:54:27.813458Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
mysql_1    | 2019-04-03T13:54:27.813850Z 0 [Warning] CA certificate ca.pem is self signed.
mysql_1    | 2019-04-03T13:54:27.815401Z 0 [Note] InnoDB: Buffer pool(s) load completed at 190403 13:54:27
mysql_1    | 2019-04-03T13:54:27.817506Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
mysql_1    | 2019-04-03T13:54:27.817571Z 0 [Note] IPv6 is available.
mysql_1    | 2019-04-03T13:54:27.817586Z 0 [Note]   - '::' resolves to '::';
mysql_1    | 2019-04-03T13:54:27.817609Z 0 [Note] Server socket created on IP: '::'.
shinobi_1  | mysqld is alive
mysql_1    | 2019-04-03T13:54:27.858410Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql_1    | 2019-04-03T13:54:27.860253Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
mysql_1    | 2019-04-03T13:54:27.860295Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
mysql_1    | 2019-04-03T13:54:27.860317Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1    | 2019-04-03T13:54:27.860363Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
mysql_1    | 2019-04-03T13:54:27.860375Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1    | 2019-04-03T13:54:27.860401Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
mysql_1    | 2019-04-03T13:54:27.862369Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
mysql_1    | 2019-04-03T13:54:27.862382Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1    | 2019-04-03T13:54:27.867897Z 0 [Note] Event Scheduler: Loaded 0 events
mysql_1    | 2019-04-03T13:54:27.868069Z 0 [Note] mysqld: ready for connections.
mysql_1    | Version: '5.7.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
mysql_1    | 2019-04-03T13:54:56.846993Z 2 [Note] Access denied for user 'root'@'localhost' (using password: NO)
mysql_1    | 2019-04-03T13:55:27.125636Z 3 [Note] Access denied for user 'root'@'localhost' (using password: NO)
mysql_1    | 2019-04-03T13:55:57.393204Z 4 [Note] Access denied for user 'root'@'localhost' (using password: NO)
mysql_1    | 2019-04-03T13:56:27.706432Z 5 [Note] Access denied for user 'root'@'localhost' (using password: NO)
mysql_1    | 2019-04-03T13:56:57.918664Z 6 [Note] Access denied for user 'root'@'localhost' (using password: NO)
mysql_1    | 2019-04-03T13:57:28.129727Z 7 [Note] Access denied for user 'root'@'localhost' (using password: NO)
mysql_1    | 2019-04-03T13:57:58.512875Z 8 [Note] Access denied for user 'root'@'localhost' (using password: NO)
shinobi_1  | Create database schema if it does not exists ...
shinobi_1  | Set keys for CRON and PLUGINS from environment variables ...
shinobi_1  | Starting Shinobi ...
shinobi_1  | 2019-04-03T08:58:06: PM2 log: Launching in no daemon mode
shinobi_1  | 2019-04-03T08:58:06: PM2 log: App [Camera-App:0] starting in -fork mode-
shinobi_1  | 2019-04-03T08:58:06: PM2 log: App [Cron-App:1] starting in -fork mode-
shinobi_1  | 2019-04-03T08:58:06: PM2 log: App [Camera-App:0] online
shinobi_1  | 2019-04-03T08:58:06: PM2 log: App [Cron-App:1] online
shinobi_1  | No "ffbinaries". Continuing.
shinobi_1  | Run "npm install ffbinaries" to get this static FFmpeg downloader.
shinobi_1  | No "ffmpeg-static".
shinobi_1  | Available Hardware Acceleration Methods :  cuvid
shinobi_1  | Shinobi : cron.js started
shinobi_1  | FFmpeg version : 3.3.4-static http://johnvansickle.com/ffmpeg/
shinobi_1  | Node.js version : v8.15.1
shinobi_1  | Shinobi : Web Server Listening on 8080
shinobi_1  | { Error: ER_INVALID_DEFAULT: Invalid default value for 'end'
shinobi_1  |     at Query.Sequence._packetToError (/opt/shinobi/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
shinobi_1  |     at Query.ErrorPacket (/opt/shinobi/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
shinobi_1  |     at Protocol._parsePacket (/opt/shinobi/node_modules/mysql/lib/protocol/Protocol.js:278:23)
shinobi_1  |     at Parser.write (/opt/shinobi/node_modules/mysql/lib/protocol/Parser.js:76:12)
shinobi_1  |     at Protocol.write (/opt/shinobi/node_modules/mysql/lib/protocol/Protocol.js:38:16)
shinobi_1  |     at Socket.<anonymous> (/opt/shinobi/node_modules/mysql/lib/Connection.js:91:28)
shinobi_1  |     at Socket.<anonymous> (/opt/shinobi/node_modules/mysql/lib/Connection.js:502:10)
shinobi_1  |     at emitOne (events.js:116:13)
shinobi_1  |     at Socket.emit (events.js:211:7)
shinobi_1  |     at addChunk (_stream_readable.js:263:12)
shinobi_1  |     at readableAddChunk (_stream_readable.js:250:11)
shinobi_1  |     at Socket.Readable.push (_stream_readable.js:208:10)
shinobi_1  |     at TCP.onread (net.js:601:20)
shinobi_1  |     --------------------
shinobi_1  |     at Protocol._enqueue (/opt/shinobi/node_modules/mysql/lib/protocol/Protocol.js:144:48)
shinobi_1  |     at Connection.query (/opt/shinobi/node_modules/mysql/lib/Connection.js:200:25)
shinobi_1  |     at /opt/shinobi/node_modules/knex/lib/dialects/mysql/index.js:144:18
shinobi_1  |     at Promise._execute (/opt/shinobi/node_modules/bluebird/js/release/debuggability.js:313:9)
shinobi_1  |     at Promise._resolveFromExecutor (/opt/shinobi/node_modules/bluebird/js/release/promise.js:483:18)
shinobi_1  |     at new Promise (/opt/shinobi/node_modules/bluebird/js/release/promise.js:79:10)
shinobi_1  |     at Client_MySQL._query (/opt/shinobi/node_modules/knex/lib/dialects/mysql/index.js:135:12)
shinobi_1  |     at Client_MySQL.query (/opt/shinobi/node_modules/knex/lib/client.js:192:17)
shinobi_1  |     at Runner.<anonymous> (/opt/shinobi/node_modules/knex/lib/runner.js:138:36)
shinobi_1  |     at Runner.tryCatcher (/opt/shinobi/node_modules/bluebird/js/release/util.js:16:23)
shinobi_1  |     at Runner.query (/opt/shinobi/node_modules/bluebird/js/release/method.js:15:34)
shinobi_1  |     at /opt/shinobi/node_modules/knex/lib/runner.js:47:21
shinobi_1  |     at tryCatcher (/opt/shinobi/node_modules/bluebird/js/release/util.js:16:23)
shinobi_1  |     at /opt/shinobi/node_modules/bluebird/js/release/using.js:185:26
shinobi_1  |     at tryCatcher (/opt/shinobi/node_modules/bluebird/js/release/util.js:16:23)
shinobi_1  |     at Promise._settlePromiseFromHandler (/opt/shinobi/node_modules/bluebird/js/release/promise.js:512:31)
shinobi_1  |   code: 'ER_INVALID_DEFAULT',
shinobi_1  |   errno: 1067,
shinobi_1  |   sqlMessage: 'Invalid default value for \'end\'',
shinobi_1  |   sqlState: '42000',
shinobi_1  |   index: 0,
shinobi_1  |   sql: 'CREATE TABLE IF NOT EXISTS `Timelapses` (`ke` varchar(50) NOT NULL,`mid` varchar(50) NOT NULL,`details` longtext,`date` date NOT NULL,`time` timestamp NOT NULL,`end` timestamp NOT NULL,`size` int(11)NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;' }
shinobi_1  | 2019-04-03T08:58:10-05:00 Shinobi is ready.
mysql_1    | 2019-04-03T13:58:28.766883Z 18 [Note] Access denied for user 'root'@'localhost' (using password: NO)
mysql_1    | 2019-04-03T13:58:59.049656Z 19 [Note] Access denied for user 'root'@'localhost' (using password: NO)
mysql_1    | 2019-04-03T13:59:29.451954Z 20 [Note] Access denied for user 'root'@'localhost' (using password: NO)

**Comment by acobaugh** [comment]
This was the healthcheck. I completely changed how environment variables are being used, so please give it a test and see how it works now.
