### ISSUE TITLE
Issue fetching from dl-cdn.alpinelinux

### ISSUE THREAD

**Issue by nalr** [acobaugh/shinobi-docker#8]
Getting this error.

fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.70f61090.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.ca2fea5b.tar.gz: No such file or directory
2 errors; 16 distinct packages available

Any thoughts on fixing?

**Comment by acobaugh** [comment]
Unable to reproduce this. Looks like either a temporary issue with alpine's CDN or a local network issue.
